### ISSUE TITLE
list > debug: segfaults

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#514]
- [ ] **Describe the bug**<br/>
 See topic.

- [ ] **To Reproduce**<br/>
1. Open a Shell
2. Enter "list > debug:"

- [ ] **Expected behaviour**<br/>
Printing a directory listing without segfaulting

- [ ] **Screenshots**<br/>

- [ ] **Architecture**<br/>
 - linux (hosted)
 
Not yet tested:
 - Amiga (including UAE, Vampire cards)
 - pc (native)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
- [ ] **CPU**<br/>
 - x86_64

Not yet tested
 - i386
 - m68k
 - arm
 - ppc
 - other:

- [ ] **Version**<br/>
Provide the Git ID from AboutAROS (call menu Wanderer>AROS>About)

- [ ] **Additional context**<br/>
Other commands are working without crashing:
dir > debug:
type s:startup-sequence to debug:
echo bla to debug:

Backtrace:
#0  0x000000005f4048a1 in REMOVE_HEADER (sl=31, fl=3, b=0x411cb800, tlsf=0x41000110) at /home/mazze/projects/aros-src/rom/kernel/./tlsf.c:311
#1  tlsf_malloc (mhe=0x41000050, size=912, flags=0x411399d4) at /home/mazze/projects/aros-src/rom/kernel/./tlsf.c:416
#2  0x000000005f423f25 in nommu_AllocMem (byteSize=912, flags=0, loc=0x41139a40, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./memory_nommu.c:48
#3  0x000000005f411b1e in Exec_33_AllocMem (byteSize=912, requirements=0, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./allocmem.c:118
#4  0x000000005f41202f in __inline_Exec_AllocMem (__arg1=784, __arg2=0, __SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/exec/exec/include/inline/exec.h:398
#5  0x000000005f412073 in Exec_114_AllocVec (byteSize=784, requirements=0, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./allocvec.c:64
#6  0x000000005f49dffb in __inline_Exec_AllocVec (__arg1=768, __arg2=0, __SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/exec.h:1646
#7  0x000000005f49e6c1 in LDNewObjectNode (name=0x5f4313e0 "intuition.library", SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/lddemon/./lddemon.c:286
#8  0x000000005f49e8d5 in LDRequestObject (libname=0x5f4313e0 "intuition.library", version=0, dir=0x5f4a0ce1 "libs", list=0x41002b10, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/lddemon/./lddemon.c:375
#9  0x000000005f49ed44 in Lddemon_0_OpenLibrary (libname=0x5f4313e0 "intuition.library", version=0, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/lddemon/./lddemon.c:514
#10 0x000000005f41c126 in __inline_Exec_OpenLibrary (__arg1=0x5f4313e0 "intuition.library", __arg2=0, __SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/exec/exec/include/inline/exec.h:1306
#11 0x000000005f41c16c in Exec_135_TaggedOpenLibrary (tag=3, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./taggedopenlibrary.c:96
#12 0x000000005f41ea0e in __inline_Exec_TaggedOpenLibrary (__arg1=3, __SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/exec/exec/include/inline/exec.h:1927
#13 0x000000005f41ed45 in Alert_AskSuspend (task=0x4115c060, alertNum=16777228, buffer=0x41161a00 "\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300\255\333\336\300"..., SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./useralert.c:61
#14 0x000000005f41efcd in AskSuspend (task=0x4115c060, alertNum=16777228, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./useralert.c:112
#15 0x000000005f41f0ee in Exec_UserAlert (alertNum=16777228, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./useralert.c:179
#16 0x000000005f410c30 in Exec_ExtAlert (alertNum=16777228, location=0x5f4169c3 <__inline_Exec_FreeMem+57>, stack=0x0, type=2 '\002', data=0x4113a170, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./alert.c:151
#17 0x000000005f4250cf in CheckHeader (header=0x411cb340, byteSize=1073, loc=0x4113a230, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./mungwall.c:161
#18 0x000000005f42518d in MungWall_Check (memoryBlock=0x411cb3a0, byteSize=1073, loc=0x4113a230, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./mungwall.c:210
#19 0x000000005f416798 in Exec_35_FreeMem (memoryBlock=0x411cb3a0, byteSize=1073, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./freemem.c:73
#20 0x000000005f4169c3 in __inline_Exec_FreeMem (__arg1=0x411cb3a0, __arg2=1073, __SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/exec/exec/include/inline/exec.h:430
#21 0x000000005f416a03 in Exec_115_FreeVec (memoryBlock=0x411cb3a0, SysBase=0x41002820) at /home/mazze/projects/aros-src/rom/exec/./freevec.c:54
#22 0x000000004115cc5e in __inline_Exec_FreeVec (__arg1=0x411cb3b0, __SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/exec.h:1662
#23 0x000000004115cda1 in debugClose (pa=0x411cb3b0, SysBase=0x41002820) at /home/mazze/projects/aros-src/workbench/fs/debug/./debug-handler.c:50
#24 0x000000004115d28f in debug_handler (SysBase=0x41002820) at /home/mazze/projects/aros-src/workbench/fs/debug/./debug-handler.c:141
#25 0x000000004115c741 in debug_Handler (argptr=0x0, argsize=0, SysBase=0x41002820) at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/workbench/fs/debug/debug/debug_start.c:90
#26 0x000000005f51106c in CallEntry (argptr=0x0, argsize=0, entry=0x4115c6ac, me=0x4115c060) at /home/mazze/projects/aros-src/rom/dos/./exit.c:129
#27 0x000000005f50cb7a in DosEntry () at /home/mazze/projects/aros-src/rom/dos/./createnewproc.c:752

**Comment by mattrust** [comment]
I can't reproduce the problem anymore.
