### ISSUE TITLE
Crash with GIF images

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#590]
**Describe the bug**
Open a GIF image with e.g. multiview causes a crash in datatypes.library. It doesn't matter if it's animated or not. Crash disappears when I delete the file:
Devs/DataTypes/.GIFAnim.x86_64

**To Reproduce**
1. Start AROS which must have the GIF animation datatypes from contrib
2. Open a Shell and do "multiview test.gif"

**Expected behaviour**
Don't crash

**Screenshots**
n/a

**Architecture**
 - linux (hosted)

Not yet tested
 - Amiga (including UAE, Vampire cards)
 - pc (native)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
**CPU**
 - x86_64
 
Not yet tested
 - i386
 - m68k
 - arm
 - ppc
 - other:

**Version**
Provide the Git ID from AboutAROS (call menu Wanderer>AROS>About)

**Additional context**
Backtrace:
#0  0x00000000412fd010 in __inline_Dos_Read (__arg1=0x41c6c860, __arg2=0x4119df10, __arg3=1103546464, __DOSBase=0x4127f455) at /home/mazze/projects/fullaros/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/dos.h:59
#1  0x00000000412f1150 in FindDtInList (DataTypesBase=0x41239c90, dthc=0x41c6c860, list=0x4123a7c0, CheckArray=0x4110a850 "GIF89a\036", CheckSize=64, Filename=0x4110a6bc "test.gif") at /home/mazze/projects/fullaros/aros-src/workbench/libs/datatypes/./helpfuncs.c:407
#2  0x00000000412f15a9 in ExamineData (DataTypesBase=0x41239c90, dthc=0x41c6c860, prevdt=0x0, CheckArray=0x4110a850 "GIF89a\036", CheckSize=64, Filename=0x4110a6bc "test.gif", Size=152) at /home/mazze/projects/fullaros/aros-src/workbench/libs/datatypes/./helpfuncs.c:504
#3  0x00000000412f0db2 in ExamineLock (lock=0x411060a0, fib=0x4110a6b0, prevdt=0x0, DataTypesBase=0x41239c90) at /home/mazze/projects/fullaros/aros-src/workbench/libs/datatypes/./helpfuncs.c:276
#4  0x00000000412ee595 in DataTypes_6_ObtainDataTypeA (type=2, handle=0x411060a0, attrs=0x41c6cd90, DataTypesBase=0x41239c90) at /home/mazze/projects/fullaros/aros-src/workbench/libs/datatypes/./obtaindatatypea.c:106
#5  0x00000000412eda3c in __inline_DataTypes_ObtainDataTypeA (__arg1=2, __arg2=0x411060a0, __arg3=0x41c6cd90, __DataTypesBase=0x41239c90) at /home/mazze/projects/fullaros/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/workbench/libs/datatypes/datatypes/include/inline/datatypes.h:28
#6  0x00000000412edd71 in DataTypes_8_NewDTObjectA (name=0x41106010, attrs=0x41c6cd90, DataTypesBase=0x41239c90) at /home/mazze/projects/fullaros/aros-src/workbench/libs/datatypes/./newdtobjecta.c:183
#7  0x00000000417cc437 in __inline_DataTypes_NewDTObjectA (__arg1=0x41106010, __arg2=0x41c6cd90, __DataTypesBase=0x41239c90) at /home/mazze/projects/fullaros/aros-linux-x86_64-dbg/bin/linux-x86_64/AROS/Developer/include/inline/datatypes.h:68
#8  0x00000000417cee60 in OpenDTO () at /home/mazze/projects/fullaros/aros-src/workbench/utilities/MultiView/./main.c:700
#9  0x00000000417d217c in InitWin () at /home/mazze/projects/fullaros/aros-src/workbench/utilities/MultiView/./main.c:1711

**Comment by mattrust** [comment]
Can't reproduce the bug anymore.
