### ISSUE TITLE
"Dir" on a file in RAM: crashes

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#80]
**Describe the bug**
Doing "Dir" on a file on the RAM disk causes a segfault.

**To Reproduce**
1. Open a Shell.
2. Do e.g. "cd ram:env"
3. Do e.g. "dir hdaudio.config"

> (gdb) bt
> #0  0x0000000044244449 in GetRealObject (object=0x411d6150)
>     at /home/mazze/projects/aros-src/rom/filesys/ram/./filesystem.c:1409
> #1  0x0000000044240e44 in CmdExamineAll (handler=0x412ade80, lock=0x412aaca0, 
>     buffer=0x41e0b500 "", size=4096, type=6, control=0x41db1f80)
>     at /home/mazze/projects/aros-src/rom/filesys/ram/./commands.c:1421
> #2  0x000000004423ea9d in RAMMain (SysBase=0x41002820)
>     at /home/mazze/projects/aros-src/rom/filesys/ram/./handler.c:262
> #3  0x000000004423db01 in ram_Handler (argptr=0x0, argsize=0, 
>     SysBase=0x41002820)
>     at /home/mazze/projects/aros-linux-x86_64-dbg/bin/linux-x86_64/gen/rom/filesys/ram/ram/ram_start.c:84
> #4  0x000000004410fa01 in CallEntry (argptr=0x0, argsize=0, entry=0x411546dc, 
>     me=0x411da9b0) at /home/mazze/projects/aros-src/rom/dos/./exit.c:129
> #5  0x000000004410b519 in DosEntry ()
>     at /home/mazze/projects/aros-src/rom/dos/./createnewproc.c:752
> #6  0x000000004400cb60 in ?? ()
> #7  0x0000000000000000 in ?? ()
> (gdb) frame 0
> #0  0x0000000044244449 in GetRealObject (object=0x411d6150)
>     at /home/mazze/projects/aros-src/rom/filesys/ram/./filesystem.c:1409
> 1409	      while((pred = node->mln_Pred) != NULL)
> (gdb) p node
> $19 = (struct MinNode *) 0x20
> 
> 

**Expected behavior**
Should either list the file or print an error message.

**Screenshots**

**Architecture**
 - linux (hosted)

not yet tested:
 - Amiga (including UAE, Vampire cards)
 - pc (native)
 - Raspberry Pi
 - mingw
 - darwin
 - other:
 
**CPU**
 - x86_64
 - i386

not yet tested:
 - m68k
 - arm
 - ppc
 - other:

**Version**
Provide the GID ID from AboutAROS (call menu Wanderer>AROS>About)

**Additional context**

**Comment by mattrust** [comment]
Crashes on i386, too:
(gdb) bt
#0  0xf3a4cb2e in StrSize (s=0x4555513b <error: Cannot access memory at address 0x4555513b>)
    at /home/mazze/projects/aros-src/rom/filesys/ram/./support.c:235
#1  0xf3a499c2 in CmdExamineAll (handler=0xf4bfd2b0, lock=0xf4c0d2c0, buffer=0xf550dfc4 "", size=4060, type=6, control=0xf54e99e0)
    at /home/mazze/projects/aros-src/rom/filesys/ram/./commands.c:1397
#2  0xf3a480a6 in RAMMain (SysBase=0xf4a501e0) at /home/mazze/projects/aros-src/rom/filesys/ram/./handler.c:262
#3  0xf3a47492 in ram_Handler (argptr=0x0, argsize=0, SysBase=0xf4a501e0)
    at /home/mazze/projects/aros-linux-i386-dbg/bin/linux-i386/gen/rom/filesys/ram/ram/ram_start.c:84
#4  0xf3981f0e in ?? ()
#5  0xf397eaca in ?? ()
#6  0xf38dd176 in ?? ()
(gdb) frame 0
#0  0xf3a4cb2e in StrSize (s=0x4555513b <error: Cannot access memory at address 0x4555513b>)
    at /home/mazze/projects/aros-src/rom/filesys/ram/./support.c:235
235	      while(*p != '\0')
(gdb) list
230	
231	   p = s;
232	
233	   if(s != NULL)
234	   {
235	      while(*p != '\0')
236	         p++;
237	      length = p - s + 1;
238	   }
239	
(gdb) p p
$7 = (const TEXT *) 0x4555513b <error: Cannot access memory at address 0x4555513b>
